server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Simple static config for API container logs
  - job_name: streams-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: streams-api
          __path__: /var/lib/docker/containers/*/streams-api-*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time
      - json:
          expressions:
            message: output
          source: output
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message

  # Direct container logs with minimal processing
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          service: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            timestamp: time
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: output