version: "3.8"

services:
  # MongoDB Database (Unified Configuration)
  mongodb:
    image: mongo:7
    container_name: streams-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-streams_poc}
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
    command: >
      mongod
      --wiredTigerCacheSizeGB 0.25
      --slowms 100
      --profile 1
    networks:
      - streams-network
    labels:
      - "coroot.service=mongodb"
      - "coroot.version=7.0"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Web API Service (Unified Configuration)
  api:
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: streams-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-streams_poc}?authSource=admin
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
    networks:
      - streams-network
    labels:
      - "coroot.service=streams-api"
      - "coroot.version=1.0.0"

  # Coroot Community Edition
  coroot:
    image: ghcr.io/coroot/coroot:latest
    container_name: coroot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - BOOTSTRAP_CLICKHOUSE_ADDRESS=clickhouse:9000
    depends_on:
      - clickhouse
    networks:
      - streams-network
    volumes:
      - coroot-data:/data

  # Coroot Node Agent (Collects system metrics)
  coroot-node-agent:
    image: ghcr.io/coroot/coroot-node-agent:latest
    container_name: coroot-node-agent
    restart: unless-stopped
    privileged: true
    pid: host
    ports:
      - "8082:80"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LISTEN=0.0.0.0:80
    networks:
      - streams-network

  # ClickHouse for storing metrics data
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./monitoring/clickhouse-config.xml:/etc/clickhouse-server/config.d/custom.xml:ro
    networks:
      - streams-network

networks:
  streams-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  coroot-data:
    driver: local
  clickhouse-data:
    driver: local
