apiVersion: 1

datasources:
  # Prometheus data source for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      timeInterval: "1s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: false
      prometheusType: "Prometheus"
      prometheusVersion: "2.47.0"
      cacheLevel: "Low"
      incrementalQuerying: false

  # Loki data source for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki
    jsonData:
      maxLines: 1000
      timeout: 60