apiVersion: 1

datasources:
  # Prometheus data source for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "1s"        # 1-second resolution for PoC
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: false
      prometheusType: "Prometheus"
      prometheusVersion: "2.47.0"
      cacheLevel: "Low"         # Low cache for real-time data
      incrementalQuerying: false # Disable for consistent real-time updates
      exemplarTraceIdDestinations: []

  # Loki data source for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000            # Higher line limit for detailed logs
      timeout: 60
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: "request_id=([\\w-]+)"
          name: "request_id"
          url: "/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22{request_id=%5C%22$${__value.raw}%5C%22}%22%7D%5D"