global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Coroot Node Agent
  - job_name: 'coroot-node-agent'
    static_configs:
      - targets: ['coroot-node-agent:80']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # MongoDB Exporter
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Streams API (metrics endpoint)
  - job_name: 'streams-api'
    static_configs:
      - targets: ['api:3000']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
